---
- name: Create a security group, open ports 22 and 80
  ec2_group:
    name       : "{{ security_group }}"
    description: Security Group for the server with port 22, 80, 443
    region     : "{{ region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port  : 22
        cidr_ip  : 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port  : 80
        cidr_ip  : 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port  : 443
        cidr_ip  : 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Create AWS EC2 Server
  ec2:
    key_name     : "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image        : "{{ image }}"
    group        : "{{ security_group }}"
    region       : "{{ region }}"
    instance_tags:
      Name: AnsibleTestTask
      Type: AnsibleEC2-SRE
    count        : "{{ count }}"
    wait         : true
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- name : Print all EC2 variables
  debug: var=ec2

- name : Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: awsserver
  loop: "{{ ec2.instances }}"
  
- name: Wait for SSH in Instance
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    state: started
  loop: "{{ ec2.instances }}"
